import { access, mkdir, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import type { ProjectManifest } from "../core/types.js";
import { envContract, envExample } from "../core/env-contract.js";
import { r2CorsJson } from "../providers/cloudflare-plan.js";

export interface GeneratedFile {
  path: string;
  content: string;
}

export interface GenerateAppResult {
  root: string;
  written: string[];
  skipped: string[];
}

async function exists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

async function writeGeneratedFile(root: string, file: GeneratedFile, force: boolean): Promise<"written" | "skipped"> {
  const target = join(root, file.path);

  if (!force && await exists(target)) {
    return "skipped";
  }

  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, file.content, "utf8");
  return "written";
}

export function createAppFiles(manifest: ProjectManifest): GeneratedFile[] {
  const packageName = manifest.slug;
  const domain = manifest.domain ?? `${manifest.slug}.vercel.app`;
  const envNames = envContract.map((variable) => variable.name);

  return [
    {
      path: "package.json",
      content: `${JSON.stringify({
        name: packageName,
        version: "0.1.0",
        private: true,
        type: "module",
        scripts: {
          dev: "next dev",
          build: "prisma generate && next build",
          start: "next start",
          check: "tsc --noEmit",
          "db:generate": "prisma generate",
          "db:migrate": "prisma migrate deploy",
          "db:studio": "prisma studio"
        },
        dependencies: {
          "@aws-sdk/client-s3": "^3.850.0",
          "@prisma/client": "^6.12.0",
          "@sentry/nextjs": "^9.39.0",
          "mixpanel": "^0.18.1",
          next: "^15.4.0",
          react: "^19.1.0",
          "react-dom": "^19.1.0",
          resend: "^4.6.0",
          "zod": "^3.25.0"
        },
        devDependencies: {
          "@types/node": "^24.0.15",
          "@types/react": "^19.1.8",
          prisma: "^6.12.0",
          typescript: "^5.8.3"
        }
      }, null, 2)}\n`
    },
    {
      path: "tsconfig.json",
      content: `{
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["dom", "dom.iterable", "ES2022"],
    "allowJs": false,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./*"]
    },
    "plugins": [{ "name": "next" }]
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
`
    },
    {
      path: ".gitignore",
      content: `.next/
node_modules/
.env
.env.local
.env*.local
dist/
.DS_Store
`
    },
    {
      path: ".env.example",
      content: envExample(manifest, "development")
    },
    {
      path: ".stacksmith/r2-cors.json",
      content: r2CorsJson(manifest)
    },
    {
      path: "next.config.ts",
      content: `import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  reactStrictMode: true
};

export default nextConfig;
`
    },
    {
      path: "app/layout.tsx",
      content: `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "${manifest.name}",
  description: "Generated by Stacksmith."
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`
    },
    {
      path: "app/page.tsx",
      content: `import { deployment } from "@/lib/deployment";

export default function HomePage() {
  return (
    <main className="shell">
      <section>
        <p className="eyebrow">Stacksmith app</p>
        <h1>${manifest.name}</h1>
        <p>Environment: {deployment.environment}</p>
        <p>App URL: {deployment.appUrl.toString()}</p>
      </section>
    </main>
  );
}
`
    },
    {
      path: "app/globals.css",
      content: `:root {
  color-scheme: light;
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  background: #f6f7f9;
  color: #181b20;
}

body {
  margin: 0;
}

.shell {
  min-height: 100vh;
  display: grid;
  place-items: center;
  padding: 32px;
}

section {
  width: min(720px, 100%);
}

h1 {
  font-size: 48px;
  line-height: 1;
  margin: 0 0 16px;
}

p {
  color: #4d5562;
}

.eyebrow {
  text-transform: uppercase;
  letter-spacing: 0;
  font-size: 12px;
  font-weight: 700;
  color: #7b3f00;
}
`
    },
    {
      path: "app/api/health/route.ts",
      content: `import { NextResponse } from "next/server";
import { deployment } from "@/lib/deployment";

export async function GET() {
  return NextResponse.json({
    status: "ok",
    project: "${manifest.slug}",
    environment: deployment.environment,
    previewId: deployment.previewId,
    gitSha: deployment.gitSha,
    appUrl: deployment.appUrl.toString(),
    apiUrl: deployment.apiUrl?.toString() ?? null
  });
}
`
    },
    {
      path: "app/.well-known/stacksmith/route.ts",
      content: `import { NextResponse } from "next/server";
import { deployment } from "@/lib/deployment";

export async function GET() {
  return NextResponse.json({
    project: "${manifest.slug}",
    environment: deployment.environment,
    previewId: deployment.previewId,
    gitSha: deployment.gitSha,
    services: {
      database: "unchecked",
      r2: "unchecked",
      resend: "unchecked",
      stripe: "unchecked",
      sentry: "configured-by-env",
      mixpanel: "configured-by-env"
    }
  });
}
`
    },
    {
      path: "lib/env.ts",
      content: `import { z } from "zod";

const envSchema = z.object({
  STACKSMITH_PROJECT: z.string().min(1),
  APP_ENV: z.enum(["development", "preview", "staging", "production"]).default("development"),
  APP_URL: z.string().url(),
  API_URL: z.string().url().optional(),
  FILES_URL: z.string().url().optional(),
  AUTH_CALLBACK_URL: z.string().url(),
  EMAIL_LINK_BASE_URL: z.string().url(),
  STRIPE_WEBHOOK_URL: z.string().url(),
  PREVIEW_ID: z.string().optional(),
  GITHUB_PR_NUMBER: z.string().optional(),
  GIT_BRANCH: z.string().optional(),
  GIT_SHA: z.string().optional(),
  DATABASE_URL: z.string().min(1),
  DIRECT_DATABASE_URL: z.string().min(1).optional(),
  R2_ACCOUNT_ID: z.string().optional(),
  R2_ACCESS_KEY_ID: z.string().optional(),
  R2_SECRET_ACCESS_KEY: z.string().optional(),
  R2_BUCKET_NAME: z.string().optional(),
  R2_PREFIX: z.string().optional(),
  R2_ENDPOINT: z.string().url().optional(),
  RESEND_API_KEY: z.string().optional(),
  EMAIL_FROM: z.string().optional(),
  SENTRY_DSN: z.string().optional(),
  NEXT_PUBLIC_SENTRY_DSN: z.string().optional(),
  MIXPANEL_TOKEN: z.string().optional(),
  NEXT_PUBLIC_MIXPANEL_TOKEN: z.string().optional()
});

export const env = envSchema.parse(process.env);

export const stacksmithEnvContract = ${JSON.stringify(envNames, null, 2)} as const;
`
    },
    {
      path: "lib/deployment.ts",
      content: `import { env } from "./env";

function optionalUrl(value: string | undefined): URL | undefined {
  return value ? new URL(value) : undefined;
}

export const deployment = {
  project: env.STACKSMITH_PROJECT,
  environment: env.APP_ENV,
  previewId: env.PREVIEW_ID || undefined,
  githubPrNumber: env.GITHUB_PR_NUMBER || undefined,
  gitBranch: env.GIT_BRANCH || undefined,
  gitSha: env.GIT_SHA || undefined,
  appUrl: new URL(env.APP_URL),
  apiUrl: optionalUrl(env.API_URL),
  filesUrl: optionalUrl(env.FILES_URL),
  authCallbackUrl: new URL(env.AUTH_CALLBACK_URL),
  emailLinkBaseUrl: new URL(env.EMAIL_LINK_BASE_URL),
  stripeWebhookUrl: new URL(env.STRIPE_WEBHOOK_URL)
};
`
    },
    {
      path: "lib/observability.ts",
      content: `import { deployment } from "./deployment";
import { env } from "./env";

export type ObservabilityContext = {
  requestId?: string;
  userId?: string;
  route?: string;
  jobId?: string;
  stripeEventId?: string;
};

export function observabilityTags(context: ObservabilityContext = {}) {
  return {
    environment: deployment.environment,
    preview_id: deployment.previewId,
    github_pr: deployment.githubPrNumber,
    git_branch: deployment.gitBranch,
    git_sha: deployment.gitSha,
    request_id: context.requestId,
    user_id: context.userId,
    route: context.route,
    job_id: context.jobId,
    stripe_event_id: context.stripeEventId
  };
}

export function captureError(error: unknown, context: ObservabilityContext = {}) {
  const tags = observabilityTags(context);

  if (!env.SENTRY_DSN && process.env.NODE_ENV !== "production") {
    console.error("[observability]", { error, tags });
  }

  return { error, tags };
}

export function trackEvent(name: string, properties: Record<string, unknown> = {}) {
  return {
    name,
    properties: {
      ...properties,
      environment: deployment.environment,
      preview_id: deployment.previewId,
      git_sha: deployment.gitSha
    }
  };
}
`
    },
    {
      path: "lib/db.ts",
      content: `import { PrismaClient } from "@prisma/client";

const globalForPrisma = globalThis as unknown as { prisma?: PrismaClient };

export const db = globalForPrisma.prisma ?? new PrismaClient();

if (process.env.NODE_ENV !== "production") {
  globalForPrisma.prisma = db;
}
`
    },
    {
      path: "lib/storage.ts",
      content: `import { env } from "./env";

export function objectKey(key: string) {
  const prefix = env.R2_PREFIX ? env.R2_PREFIX.replace(/\\/$/, "") + "/" : "";
  return \`\${prefix}\${key.replace(/^\\/+/, "")}\`;
}

export function storageConfigured() {
  return Boolean(env.R2_ACCOUNT_ID && env.R2_ACCESS_KEY_ID && env.R2_SECRET_ACCESS_KEY && env.R2_BUCKET_NAME);
}
`
    },
    {
      path: "lib/email.ts",
      content: `import { env } from "./env";

export function emailConfigured() {
  return Boolean(env.RESEND_API_KEY && env.EMAIL_FROM);
}

export function defaultFromAddress() {
  return env.EMAIL_FROM ?? "hello@example.com";
}
`
    },
    {
      path: "lib/auth.ts",
      content: `export const authConfig = {
  emailOtp: true,
  magicLink: true,
  social: {
    google: false,
    github: false,
    facebook: false,
    twitter: false
  }
};
`
    },
    {
      path: "prisma/schema.prisma",
      content: `generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id        String   @id @default(cuid())
  email     String   @unique
  name      String?
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  auditEvents AuditEvent[]
}

model AuditEvent {
  id         String   @id @default(cuid())
  actorId    String?
  action     String
  entityType String
  entityId   String?
  metadata   Json     @default("{}")
  requestId  String?
  createdAt  DateTime @default(now())

  actor User? @relation(fields: [actorId], references: [id])
}

model WebhookEvent {
  id          String   @id
  provider    String
  status      String   @default("pending")
  processedAt DateTime?
  payload     Json
  createdAt   DateTime @default(now())
}
`
    },
    {
      path: "README.md",
      content: `# ${manifest.name}

Generated by Stacksmith.

## Development

Copy \`.env.example\` to \`.env.local\`, fill in values, then run:

\`\`\`bash
npm install
npm run dev
\`\`\`

Health:

\`\`\`text
GET /api/health
GET /.well-known/stacksmith
\`\`\`
`
    }
  ];
}

export async function generateAppSkeleton(input: {
  manifest: ProjectManifest;
  targetDir: string;
  force?: boolean;
}): Promise<GenerateAppResult> {
  const root = resolve(input.targetDir);
  const files = createAppFiles(input.manifest);
  const written: string[] = [];
  const skipped: string[] = [];

  await mkdir(root, { recursive: true });

  for (const file of files) {
    const result = await writeGeneratedFile(root, file, input.force ?? false);
    if (result === "written") {
      written.push(file.path);
    } else {
      skipped.push(file.path);
    }
  }

  return { root, written, skipped };
}
