import type { ExternalCommand } from "../core/commands.js";
import { envContract } from "../core/env-contract.js";
import type { EnvironmentName, ProjectManifest, ProviderId } from "../core/types.js";
import { cloudflareCommandPlan } from "./cloudflare-plan.js";
import { cloudRunProjectId, cloudRunRegion } from "./cloud-run-project.js";

export function providerCommandPlan(provider: ProviderId, manifest: ProjectManifest): ExternalCommand[] {
  switch (provider) {
    case "github":
      return githubCommandPlan(manifest);

    case "vercel":
      return vercelCommandPlan(manifest);

    case "cloud-run":
      return cloudRunCommandPlan(manifest);

    case "prisma-postgres":
      return prismaPostgresCommandPlan(manifest);

    case "cloudflare":
      return cloudflareCommandPlan(manifest);

    case "stripe":
      return stripeCommandPlan(manifest);

    default:
      return [];
  }
}

function githubCommandPlan(manifest: ProjectManifest): ExternalCommand[] {
  const provider = "github" as const;
  const visibility = manifest.providers.github.private === false ? "--public" : "--private";
  const initialCommitMessage = "Initial Stacksmith scaffold";
  const repoShell = githubRepoShell(manifest);
  const repoUrlShell = `${repoShell}; repo_url="git@github.com:$repo.git"`;
  const remoteMatchesExpected = [
    "-c",
    `${repoUrlShell}; test "$(git remote get-url origin 2>/dev/null)" = "$repo_url"`
  ];
  const headMatchesRemoteMain = [
    "-c",
    "local_sha=$(git rev-parse HEAD) && remote_sha=$(git ls-remote origin refs/heads/main | awk '{print $1}') && test \"$local_sha\" = \"$remote_sha\""
  ];

  return [
    {
      provider,
      id: "github.auth.check",
      description: "Verify the GitHub CLI is authenticated.",
      command: "gh",
      args: ["auth", "status"],
      risk: "read-only",
      requiresConfirmation: false,
      check: {
        description: "GitHub CLI authentication is available.",
        command: "gh",
        args: ["auth", "status"]
      },
      undo: {
        description: "No undo is needed for a read-only GitHub authentication check.",
        command: "sh",
        args: ["-c", "true"],
        risk: "read-only",
        requiresConfirmation: false
      }
    },
    {
      provider,
      id: "github.git.init",
      description: "Initialize a local Git repository if this project does not have one.",
      command: "sh",
      args: ["-c", "git init -b main && git config stacksmith.managed true"],
      risk: "reversible",
      requiresConfirmation: true,
      check: {
        description: "Local Git repository exists.",
        command: "test",
        args: ["-d", ".git"]
      },
      undo: {
        description: "Remove the local Git repository only if Stacksmith initialized it.",
        command: "rm",
        args: ["-rf", ".git"],
        risk: "destructive",
        requiresConfirmation: true,
        check: {
          description: "Local Git repository was initialized by Stacksmith.",
          command: "sh",
          args: ["-c", "test \"$(git config --bool stacksmith.managed 2>/dev/null)\" = \"true\""]
        }
      }
    },
    {
      provider,
      id: "github.git.initial-commit",
      description: "Create an initial commit when the project has no commits yet.",
      command: "sh",
      args: ["-c", `git add . && git commit -m "${initialCommitMessage}"`],
      risk: "reversible",
      requiresConfirmation: true,
      check: {
        description: "Local Git repository has a commit.",
        command: "git",
        args: ["rev-parse", "--verify", "HEAD"]
      },
      undo: {
        description: "Undo the Stacksmith-created initial commit only if it is still HEAD.",
        command: "sh",
        args: ["-c", "if git rev-parse --verify HEAD~1 >/dev/null 2>&1; then git reset --soft HEAD~1; else git update-ref -d HEAD; fi"],
        risk: "destructive",
        requiresConfirmation: true,
        check: {
          description: "Latest commit is the Stacksmith initial commit.",
          command: "sh",
          args: ["-c", `test "$(git log -1 --pretty=%B 2>/dev/null)" = "${initialCommitMessage}"`]
        }
      }
    },
    {
      provider,
      id: "github.repo.create",
      description: "Create the GitHub repository.",
      command: "sh",
      args: ["-c", `${repoShell}; gh repo create "$repo" ${visibility} --description ${shSingleQuote(`${manifest.name} generated by Stacksmith`)}`],
      risk: "reversible",
      requiresConfirmation: true,
      check: {
        description: "GitHub repository exists.",
        command: "sh",
        args: ["-c", `${repoShell}; gh repo view "$repo"`]
      },
      undo: {
        description: "Delete the GitHub repository.",
        command: "sh",
        args: ["-c", `${repoShell}; gh repo delete "$repo" --yes`],
        risk: "destructive",
        requiresConfirmation: true,
        check: {
          description: "GitHub repository exists.",
          command: "sh",
          args: ["-c", `${repoShell}; gh repo view "$repo"`]
        }
      }
    },
    {
      provider,
      id: "github.remote.origin",
      description: "Point the local origin remote at the GitHub repository.",
      command: "sh",
      args: ["-c", `${repoUrlShell}; git remote add origin "$repo_url" 2>/dev/null || git remote set-url origin "$repo_url"`],
      risk: "reversible",
      requiresConfirmation: true,
      check: {
        description: "Local origin remote points at the GitHub repository.",
        command: "sh",
        args: remoteMatchesExpected
      },
      undo: {
        description: "Remove origin only when it still points at the Stacksmith-managed GitHub repository.",
        command: "git",
        args: ["remote", "remove", "origin"],
        risk: "reversible",
        requiresConfirmation: true,
        check: {
          description: "Local origin remote points at the GitHub repository.",
          command: "sh",
          args: remoteMatchesExpected
        }
      }
    },
    {
      provider,
      id: "github.repo.push",
      description: "Push the current HEAD to the GitHub main branch.",
      command: "git",
      args: ["push", "-u", "origin", "HEAD:main"],
      risk: "reversible",
      requiresConfirmation: true,
      check: {
        description: "Remote main branch matches local HEAD.",
        command: "sh",
        args: headMatchesRemoteMain
      },
      undo: {
        description: "No direct push undo is possible because GitHub refuses deleting a repository's current default branch; repository deletion tears down the pushed branch.",
        command: "sh",
        args: ["-c", "true"],
        risk: "read-only",
        requiresConfirmation: false
      }
    }
  ];
}

function shSingleQuote(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`;
}

function githubRepoShell(manifest: ProjectManifest): string {
  const owner = manifest.providers.github.owner;
  const ownerAssignment = owner
    ? `repo_owner=${shSingleQuote(owner)}`
    : "repo_owner=\"${GITHUB_OWNER:-$(gh api user --jq .login)}\"";

  return `${ownerAssignment}; repo="$repo_owner/${manifest.slug}"`;
}

function vercelCommandPlan(manifest: ProjectManifest): ExternalCommand[] {
  const provider = "vercel" as const;
  const scopeArgs = vercelScopeArgs(manifest);
  const projectInspectArgs = ["project", "inspect", manifest.slug, ...scopeArgs];
  const projectRemoveShell = [
    "printf 'y\\n' |",
    "vercel",
    "project",
    "remove",
    shSingleQuote(manifest.slug),
    ...scopeArgs.map(shSingleQuote)
  ].join(" ");

  return [
    {
      provider,
      id: "vercel.auth.check",
      description: "Verify the Vercel CLI can access the selected account or team.",
      command: "vercel",
      args: ["whoami", ...scopeArgs],
      risk: "read-only",
      requiresConfirmation: false,
      check: {
        description: "Vercel CLI authentication is available.",
        command: "vercel",
        args: ["whoami", ...scopeArgs]
      },
      undo: {
        description: "No undo is needed for a read-only Vercel authentication check.",
        command: "stacksmith",
        args: ["noop", "vercel.auth.check"],
        risk: "read-only",
        requiresConfirmation: false
      }
    },
    {
      provider,
      id: "vercel.project.create",
      description: "Create the Vercel project if it does not already exist.",
      command: "vercel",
      args: ["project", "add", manifest.slug, ...scopeArgs],
      risk: "reversible",
      requiresConfirmation: true,
      check: {
        description: "Vercel project exists.",
        command: "vercel",
        args: projectInspectArgs
      },
      undo: {
        description: "Delete the Vercel project.",
        command: "sh",
        args: ["-c", projectRemoveShell],
        risk: "destructive",
        requiresConfirmation: true,
        check: {
          description: "Vercel project exists.",
          command: "vercel",
          args: projectInspectArgs
        }
      }
    },
    {
      provider,
      id: "vercel.project.link",
      description: "Link or create the Vercel project.",
      command: "vercel",
      args: ["link", "--project", manifest.slug, "--yes", ...vercelTeamLinkArgs(manifest)],
      risk: "reversible",
      requiresConfirmation: true,
      check: {
        description: "Local Vercel project link exists.",
        command: "test",
        args: ["-f", ".vercel/project.json"]
      },
      undo: {
        description: "Remove the local Vercel project link.",
        command: "rm",
        args: ["-rf", ".vercel"],
        risk: "reversible",
        requiresConfirmation: true
      }
    },
    ...vercelDomainCommands(manifest),
    ...vercelEnvCommands(manifest)
  ];
}

function prismaPostgresCommandPlan(manifest: ProjectManifest): ExternalCommand[] {
  const provider = "prisma-postgres" as const;
  const config = manifest.providers["prisma-postgres"];
  const region = config.region ?? "iad1";
  const billingPlan = config.billingPlan ?? "free";
  const productId = "prisma-postgres";
  const authFile = ".stacksmith/prisma-authorization.json";
  const databaseFile = ".stacksmith/prisma-database.json";
  const connectionFile = ".stacksmith/prisma-connection.json";

  const authorizeScript = [
    "const fs = await import('node:fs/promises');",
    "const teamId = process.env.VERCEL_TEAM_ID;",
    "const integrationConfigurationId = process.env.PRISMA_INTEGRATION_CONFIG_ID;",
    `const productId = process.env.PRISMA_PRODUCT_ID || ${JSON.stringify(productId)};`,
    `const billingPlanId = process.env.PRISMA_BILLING_PLAN || ${JSON.stringify(billingPlan)};`,
    `const region = process.env.PRISMA_POSTGRES_REGION || ${JSON.stringify(region)};`,
    "const response = await fetch(`https://api.vercel.com/v1/integrations/billing/authorization?teamId=${teamId}`, {",
    "  method: 'POST',",
    "  headers: { Authorization: `Bearer ${process.env.VERCEL_TOKEN}`, 'Content-Type': 'application/json' },",
    "  body: JSON.stringify({",
    "    integrationIdOrSlug: 'prisma',",
    "    productId,",
    "    billingPlanId,",
    "    metadata: JSON.stringify({ region }),",
    "    integrationConfigurationId",
    "  })",
    "});",
    "if (!response.ok) throw new Error(`Prisma billing authorization failed: ${response.status} ${await response.text()}`);",
    "await fs.mkdir('.stacksmith', { recursive: true });",
    `await fs.writeFile(${JSON.stringify(authFile)}, JSON.stringify(await response.json(), null, 2) + '\\n');`
  ].join(" ");

  const createDatabaseScript = [
    "const fs = await import('node:fs/promises');",
    "const authorizationData = JSON.parse(await fs.readFile('.stacksmith/prisma-authorization.json', 'utf8'));",
    "const authorization = authorizationData.authorization ?? authorizationData;",
    "const teamId = process.env.VERCEL_TEAM_ID;",
    "const configId = process.env.PRISMA_INTEGRATION_CONFIG_ID || authorization.integrationConfigurationId;",
    "const authorizationId = process.env.PRISMA_AUTHORIZATION_ID || authorization.id;",
    `const productId = process.env.PRISMA_PRODUCT_ID || ${JSON.stringify(productId)};`,
    `const billingPlanId = process.env.PRISMA_BILLING_PLAN || ${JSON.stringify(billingPlan)};`,
    `const region = process.env.PRISMA_POSTGRES_REGION || ${JSON.stringify(region)};`,
    "const response = await fetch(`https://api.vercel.com/v1/storage/stores/integration?teamId=${teamId}`, {",
    "  method: 'POST',",
    "  headers: { Authorization: `Bearer ${process.env.VERCEL_TOKEN}`, 'Content-Type': 'application/json' },",
    "  body: JSON.stringify({",
    "    metadata: { region },",
    "    billingPlanId,",
    `    name: ${JSON.stringify(`${manifest.slug}-production`)},`,
    "    integrationConfigurationId: configId,",
    "    integrationProductIdOrSlug: productId,",
    "    authorizationId,",
    "    source: 'marketplace'",
    "  })",
    "});",
    "if (!response.ok) throw new Error(`Prisma database creation failed: ${response.status} ${await response.text()}`);",
    `await fs.writeFile(${JSON.stringify(databaseFile)}, JSON.stringify(await response.json(), null, 2) + '\\n');`
  ].join(" ");

  const connectDatabaseScript = [
    "const fs = await import('node:fs/promises');",
    "const vercelProject = JSON.parse(await fs.readFile('.vercel/project.json', 'utf8'));",
    "const databaseData = JSON.parse(await fs.readFile('.stacksmith/prisma-database.json', 'utf8'));",
    "const store = databaseData.store ?? databaseData;",
    "const teamId = process.env.VERCEL_TEAM_ID;",
    "const projectId = process.env.VERCEL_PROJECT_ID || vercelProject.projectId;",
    "const configId = process.env.PRISMA_INTEGRATION_CONFIG_ID;",
    `const productId = process.env.PRISMA_PRODUCT_ID || ${JSON.stringify(productId)};`,
    "const response = await fetch(`https://api.vercel.com/v1/integrations/installations/${configId}/products/${productId}/resources/${store.id}/connections?teamId=${teamId}`, {",
    "  method: 'POST',",
    "  headers: { Authorization: `Bearer ${process.env.VERCEL_TOKEN}`, 'Content-Type': 'application/json' },",
    "  body: JSON.stringify({ projectId })",
    "});",
    "if (!response.ok) throw new Error(`Prisma database connection failed: ${response.status} ${await response.text()}`);",
    `await fs.writeFile(${JSON.stringify(connectionFile)}, JSON.stringify({ projectId, storeId: store.id, connectedAt: new Date().toISOString() }, null, 2) + '\\n');`
  ].join(" ");

  return [
    {
      provider,
      id: "prisma-postgres.vercel.integration.authorize",
      description: "Authorize Prisma Postgres billing for the Vercel Marketplace integration.",
      command: "node",
      args: ["--input-type=module", "--eval", authorizeScript],
      risk: "production-write",
      requiresConfirmation: true,
      env: ["VERCEL_TOKEN", "VERCEL_TEAM_ID", "PRISMA_INTEGRATION_CONFIG_ID"],
      check: {
        description: "Prisma Vercel Marketplace authorization response is recorded.",
        command: "test",
        args: ["-f", authFile]
      },
      undo: {
        description: "Prisma billing authorizations are not deleted by Stacksmith yet; remove the marketplace authorization in Vercel if needed.",
        command: "stacksmith",
        args: ["noop", "prisma-postgres.vercel.integration.authorize"],
        risk: "read-only",
        requiresConfirmation: false
      }
    },
    {
      provider,
      id: "prisma-postgres.vercel.database.create",
      description: "Create the Prisma Postgres production database through Vercel Marketplace APIs.",
      command: "node",
      args: ["--input-type=module", "--eval", createDatabaseScript],
      risk: "production-write",
      requiresConfirmation: true,
      env: ["VERCEL_TOKEN", "VERCEL_TEAM_ID"],
      check: {
        description: "Prisma Postgres database response is recorded.",
        command: "test",
        args: ["-f", databaseFile]
      },
      undo: {
        description: "Prisma database deletion is not implemented in Stacksmith yet; delete the marketplace store from Vercel/Prisma before rerunning destructive tests.",
        command: "stacksmith",
        args: ["noop", "prisma-postgres.vercel.database.create"],
        risk: "read-only",
        requiresConfirmation: false
      }
    },
    {
      provider,
      id: "prisma-postgres.vercel.database.connect",
      description: "Connect the Prisma Postgres database to the local Vercel project for env injection.",
      command: "node",
      args: ["--input-type=module", "--eval", connectDatabaseScript],
      risk: "production-write",
      requiresConfirmation: true,
      env: ["VERCEL_TOKEN", "VERCEL_TEAM_ID", "PRISMA_INTEGRATION_CONFIG_ID"],
      check: {
        description: "Prisma Postgres Vercel connection response is recorded.",
        command: "test",
        args: ["-f", connectionFile]
      },
      undo: {
        description: "Prisma database disconnection is not implemented in Stacksmith yet; remove the resource connection in Vercel if needed.",
        command: "stacksmith",
        args: ["noop", "prisma-postgres.vercel.database.connect"],
        risk: "read-only",
        requiresConfirmation: false
      }
    }
  ];
}

function stripeCommandPlan(manifest: ProjectManifest): ExternalCommand[] {
  const provider = "stripe" as const;
  const webhookUrl = manifest.environments.preview.stripeWebhookUrl ?? "https://stripe-preview.example.com/webhooks";

  return [
    {
      provider,
      id: "stripe.webhook.preview-router",
      description: "Create a Stripe test-mode webhook for the preview router.",
      command: "stripe",
      args: ["webhook_endpoints", "create", "--url", webhookUrl],
      risk: "reversible",
      requiresConfirmation: true,
      env: ["STRIPE_SECRET_KEY"],
      check: {
        description: "Stripe preview webhook endpoint is listed.",
        command: "stripe",
        args: ["webhook_endpoints", "list", "--limit", "100"],
        stdoutIncludes: webhookUrl,
        env: ["STRIPE_SECRET_KEY"]
      },
      undo: {
        description: "Delete a Stripe webhook endpoint by id.",
        command: "stripe",
        args: ["webhook_endpoints", "delete", "$STRIPE_PREVIEW_WEBHOOK_ENDPOINT_ID"],
        risk: "destructive",
        requiresConfirmation: true,
        env: ["STRIPE_SECRET_KEY", "STRIPE_PREVIEW_WEBHOOK_ENDPOINT_ID"]
      }
    }
  ];
}

function cloudRunCommandPlan(manifest: ProjectManifest): ExternalCommand[] {
  const provider = "cloud-run" as const;
  const projectId = cloudRunProjectId(manifest);
  const region = cloudRunRegion(manifest);
  const repository = `${manifest.slug}-images`;
  const apiService = `${manifest.slug}-api`;
  const workerJob = `${manifest.slug}-worker`;

  return [
    {
      provider,
      id: "cloud-run.project.create",
      description: "Create the Google Cloud project Stacksmith will manage for this app.",
      command: "gcloud",
      args: ["projects", "create", projectId, "--name", manifest.name, "--set-as-default"],
      risk: "production-write",
      requiresConfirmation: true,
      check: {
        description: "Google Cloud project exists.",
        command: "gcloud",
        args: ["projects", "describe", projectId]
      },
      undo: {
        description: "Delete the Google Cloud project.",
        command: "gcloud",
        args: ["projects", "delete", projectId, "--quiet"],
        risk: "destructive",
        requiresConfirmation: true
      }
    },
    {
      provider,
      id: "cloud-run.billing.link",
      description: "Link the Google Cloud project to the selected billing account.",
      command: "gcloud",
      args: ["billing", "projects", "link", projectId, "--billing-account", "$GOOGLE_CLOUD_BILLING_ACCOUNT_ID"],
      risk: "production-write",
      requiresConfirmation: true,
      env: ["GOOGLE_CLOUD_BILLING_ACCOUNT_ID"],
      check: {
        description: "Google Cloud project billing is enabled.",
        command: "gcloud",
        args: ["billing", "projects", "describe", projectId, "--format=value(billingEnabled)"],
        stdoutIncludes: "True"
      },
      undo: {
        description: "Unlink billing from the Google Cloud project.",
        command: "gcloud",
        args: ["billing", "projects", "unlink", projectId],
        risk: "production-write",
        requiresConfirmation: true
      }
    },
    {
      provider,
      id: "cloud-run.services.enable",
      description: "Enable Cloud Run, Cloud Build, Artifact Registry, and Scheduler APIs.",
      command: "gcloud",
      args: [
        "services",
        "enable",
        "run.googleapis.com",
        "cloudbuild.googleapis.com",
        "artifactregistry.googleapis.com",
        "cloudscheduler.googleapis.com",
        "--project",
        projectId
      ],
      risk: "reversible",
      requiresConfirmation: true,
      check: {
        description: "Required Google APIs are enabled.",
        command: "gcloud",
        args: ["services", "list", "--enabled", "--project", projectId, "--format=value(config.name)"],
        stdoutIncludes: "run.googleapis.com"
      },
      undo: {
        description: "Disable Cloud Run related Google APIs.",
        command: "gcloud",
        args: [
          "services",
          "disable",
          "run.googleapis.com",
          "cloudbuild.googleapis.com",
          "artifactregistry.googleapis.com",
          "cloudscheduler.googleapis.com",
          "--project",
          projectId,
          "--quiet"
        ],
        risk: "destructive",
        requiresConfirmation: true
      }
    },
    {
      provider,
      id: "cloud-run.artifact-registry.create",
      description: "Create the Docker Artifact Registry repository for Cloud Run builds.",
      command: "gcloud",
      args: [
        "artifacts",
        "repositories",
        "create",
        repository,
        "--repository-format",
        "docker",
        "--location",
        region,
        "--description",
        `Stacksmith images for ${manifest.name}`,
        "--project",
        projectId
      ],
      risk: "production-write",
      requiresConfirmation: true,
      check: {
        description: "Artifact Registry repository exists.",
        command: "gcloud",
        args: ["artifacts", "repositories", "describe", repository, "--location", region, "--project", projectId]
      },
      undo: {
        description: "Delete the Artifact Registry repository.",
        command: "gcloud",
        args: ["artifacts", "repositories", "delete", repository, "--location", region, "--project", projectId, "--quiet"],
        risk: "destructive",
        requiresConfirmation: true
      }
    },
    {
      provider,
      id: "cloud-run.api.deploy",
      description: "Deploy the scale-to-zero API service to Cloud Run.",
      command: "gcloud",
      args: [
        "run",
        "deploy",
        apiService,
        "--source",
        ".",
        "--region",
        region,
        "--allow-unauthenticated",
        "--min-instances",
        "0",
        "--timeout",
        "3600",
        "--project",
        projectId
      ],
      risk: "reversible",
      requiresConfirmation: true,
      check: {
        description: "Cloud Run API service exists.",
        command: "gcloud",
        args: ["run", "services", "describe", apiService, "--region", region, "--project", projectId]
      },
      undo: {
        description: "Delete the Cloud Run API service.",
        command: "gcloud",
        args: ["run", "services", "delete", apiService, "--region", region, "--project", projectId, "--quiet"],
        risk: "destructive",
        requiresConfirmation: true
      }
    },
    {
      provider,
      id: "cloud-run.job.worker.deploy",
      description: "Deploy the background worker as a Cloud Run Job.",
      command: "gcloud",
      args: [
        "run",
        "jobs",
        "deploy",
        workerJob,
        "--source",
        ".",
        "--region",
        region,
        "--task-timeout",
        "3600",
        "--project",
        projectId
      ],
      risk: "reversible",
      requiresConfirmation: true,
      check: {
        description: "Cloud Run worker job exists.",
        command: "gcloud",
        args: ["run", "jobs", "describe", workerJob, "--region", region, "--project", projectId]
      },
      undo: {
        description: "Delete the Cloud Run worker job.",
        command: "gcloud",
        args: ["run", "jobs", "delete", workerJob, "--region", region, "--project", projectId, "--quiet"],
        risk: "destructive",
        requiresConfirmation: true
      }
    },
    {
      provider,
      id: "cloud-run.job.worker.execute",
      description: "Execute the background worker Cloud Run Job.",
      command: "gcloud",
      args: ["run", "jobs", "execute", workerJob, "--region", region, "--project", projectId],
      risk: "reversible",
      requiresConfirmation: true,
      undo: {
        description: "Cloud Run job executions are one-shot and cannot be undone.",
        command: "stacksmith",
        args: ["noop", "cloud-run.job.worker.execute"],
        risk: "read-only",
        requiresConfirmation: false
      }
    }
  ];
}

const vercelStacksmithEnvironments: EnvironmentName[] = ["development", "preview", "staging", "production"];
const dynamicPreviewVariables = new Set(["PREVIEW_ID", "GITHUB_PR_NUMBER", "GIT_BRANCH", "GIT_SHA"]);
const externallySuppliedEnvVariables = new Set([
  "DATABASE_URL",
  "DIRECT_DATABASE_URL",
  "R2_ACCOUNT_ID",
  "R2_ACCESS_KEY_ID",
  "R2_SECRET_ACCESS_KEY",
  "R2_ENDPOINT",
  "R2_EVENT_WEBHOOK_SECRET",
  "RESEND_API_KEY",
  "POSTHOG_PROJECT_API_KEY",
  "NEXT_PUBLIC_POSTHOG_KEY",
  "SLACK_ALERTS_CHANNEL_ID"
]);
const generatedPreviewOverrides: Record<string, string> = {
  R2_PREFIX: "previews/{previewId}/"
};

function vercelScopeArgs(manifest: ProjectManifest): string[] {
  return manifest.providers.vercel.team ? ["--scope", manifest.providers.vercel.team] : [];
}

function vercelTeamLinkArgs(manifest: ProjectManifest): string[] {
  return manifest.providers.vercel.team ? ["--team", manifest.providers.vercel.team] : [];
}

function vercelEnvironmentArgs(environment: EnvironmentName): string[] {
  if (environment === "staging") {
    return ["preview", "staging"];
  }

  if (environment === "production") {
    return ["production"];
  }

  if (environment === "development") {
    return ["development"];
  }

  return ["preview"];
}

function vercelEnvCheckArgs(environment: EnvironmentName): string[] {
  return ["env", "list", ...vercelEnvironmentArgs(environment)];
}

function vercelEnvAddArgs(name: string, environment: EnvironmentName): string[] {
  return ["env", "add", name, ...vercelEnvironmentArgs(environment)];
}

function vercelEnvRemoveArgs(name: string, environment: EnvironmentName): string[] {
  return ["env", "remove", name, ...vercelEnvironmentArgs(environment)];
}

function generatedEnvValue(manifest: ProjectManifest, environment: EnvironmentName, name: string): string | undefined {
  if (externallySuppliedEnvVariables.has(name)) {
    return undefined;
  }

  if (environment === "preview" && generatedPreviewOverrides[name]) {
    return generatedPreviewOverrides[name];
  }

  const variable = envContract.find((candidate) => candidate.name === name);
  const example = variable?.example(manifest, environment);

  return example ? example : undefined;
}

function vercelEnvNames(environment: EnvironmentName): string[] {
  return envContract
    .filter((variable) => variable.requiredIn.includes(environment))
    .map((variable) => variable.name)
    .filter((name) => !(environment === "preview" && dynamicPreviewVariables.has(name)));
}

function vercelDomainCommands(manifest: ProjectManifest): ExternalCommand[] {
  if (!manifest.domain || manifest.domainMode === "free") {
    return [];
  }

  const provider = "vercel" as const;
  const scopeArgs = vercelScopeArgs(manifest);

  return [
    {
      provider,
      id: "vercel.domain.add",
      description: "Attach the project production domain to Vercel. DNS remains managed by Cloudflare.",
      command: "vercel",
      args: ["domains", "add", manifest.domain, manifest.slug, ...scopeArgs],
      risk: "production-write",
      requiresConfirmation: true,
      check: {
        description: "Vercel domain exists.",
        command: "vercel",
        args: ["domains", "inspect", manifest.domain, ...scopeArgs]
      },
      undo: {
        description: "Remove the domain from Vercel. This does not change Cloudflare DNS.",
        command: "vercel",
        args: ["domains", "remove", manifest.domain, ...scopeArgs],
        risk: "production-write",
        requiresConfirmation: true,
        check: {
          description: "Vercel domain exists.",
          command: "vercel",
          args: ["domains", "inspect", manifest.domain, ...scopeArgs]
        }
      }
    },
    {
      provider,
      id: "vercel.domain.verify",
      description: "Verify the Vercel production domain DNS configuration.",
      command: "vercel",
      args: ["domains", "verify", manifest.domain, ...scopeArgs],
      risk: "read-only",
      requiresConfirmation: false,
      check: {
        description: "Vercel domain is present for verification.",
        command: "vercel",
        args: ["domains", "inspect", manifest.domain, ...scopeArgs]
      },
      undo: {
        description: "No undo is needed for a read-only Vercel domain verification.",
        command: "stacksmith",
        args: ["noop", "vercel.domain.verify"],
        risk: "read-only",
        requiresConfirmation: false
      }
    }
  ];
}

function vercelEnvCommands(manifest: ProjectManifest): ExternalCommand[] {
  const commands: ExternalCommand[] = [];

  for (const environment of vercelStacksmithEnvironments) {
    for (const name of vercelEnvNames(environment)) {
      const generatedValue = generatedEnvValue(manifest, environment, name);
      const risk = environment === "production" ? "production-write" as const : "reversible" as const;

      commands.push({
        provider: "vercel" as const,
        id: `vercel.env.${environment}.${name}`,
        description: generatedValue
          ? `Set generated ${name} for the Stacksmith ${environment} environment in Vercel.`
          : `Set secret ${name} for the Stacksmith ${environment} environment in Vercel from local env.`,
        command: "vercel",
        args: vercelEnvAddArgs(name, environment),
        risk,
        requiresConfirmation: true,
        env: generatedValue ? undefined : [name],
        stdin: generatedValue,
        stdinFromEnv: generatedValue ? undefined : name,
        check: {
          description: `${name} exists in the Stacksmith ${environment} environment on Vercel.`,
          command: "vercel",
          args: vercelEnvCheckArgs(environment),
          stdoutIncludes: name
        },
        undo: {
          description: `Remove ${name} from the Stacksmith ${environment} environment on Vercel.`,
          command: "vercel",
          args: vercelEnvRemoveArgs(name, environment),
          risk,
          requiresConfirmation: true,
          stdin: "y\n",
          check: {
            description: `${name} exists in the Stacksmith ${environment} environment on Vercel.`,
            command: "vercel",
            args: vercelEnvCheckArgs(environment),
            stdoutIncludes: name
          }
        }
      });
    }
  }

  commands.push({
    provider: "vercel" as const,
    id: "vercel.env.pull.development",
    description: "Pull Vercel development environment variables into .env.local.",
    command: "vercel",
    args: ["env", "pull", ".env.local"],
    risk: "reversible",
    requiresConfirmation: true,
    check: {
      description: ".env.local exists.",
      command: "test",
      args: ["-f", ".env.local"]
    },
    undo: {
      description: "Remove the pulled .env.local file.",
      command: "rm",
      args: ["-f", ".env.local"],
      risk: "destructive",
      requiresConfirmation: true,
      check: {
        description: ".env.local exists.",
        command: "test",
        args: ["-f", ".env.local"]
      }
    }
  });

  return commands;
}

export function allProviderCommandPlans(manifest: ProjectManifest): ExternalCommand[] {
  return (Object.keys(manifest.providers) as ProviderId[])
    .filter((provider) => manifest.providers[provider].enabled)
    .flatMap((provider) => providerCommandPlan(provider, manifest));
}
