import type { ExternalCommand } from "../core/commands.js";
import type { ProjectManifest, ProviderId } from "../core/types.js";
import { cloudflareCommandPlan } from "./cloudflare-plan.js";
import { cloudRunProjectId, cloudRunRegion } from "./cloud-run-project.js";

export function providerCommandPlan(provider: ProviderId, manifest: ProjectManifest): ExternalCommand[] {
  switch (provider) {
    case "github":
      return githubCommandPlan(manifest);

    case "vercel":
      return vercelCommandPlan(manifest);

    case "cloud-run":
      return cloudRunCommandPlan(manifest);

    case "cloudflare":
      return cloudflareCommandPlan(manifest);

    case "stripe":
      return stripeCommandPlan(manifest);

    default:
      return [];
  }
}

function githubCommandPlan(manifest: ProjectManifest): ExternalCommand[] {
  const provider = "github" as const;
  const visibility = manifest.providers.github.private === false ? "--public" : "--private";
  const initialCommitMessage = "Initial Stacksmith scaffold";
  const repoShell = githubRepoShell(manifest);
  const repoUrlShell = `${repoShell}; repo_url="git@github.com:$repo.git"`;
  const remoteMatchesExpected = [
    "-c",
    `${repoUrlShell}; test "$(git remote get-url origin 2>/dev/null)" = "$repo_url"`
  ];
  const headMatchesRemoteMain = [
    "-c",
    "local_sha=$(git rev-parse HEAD) && remote_sha=$(git ls-remote origin refs/heads/main | awk '{print $1}') && test \"$local_sha\" = \"$remote_sha\""
  ];

  return [
    {
      provider,
      id: "github.auth.check",
      description: "Verify the GitHub CLI is authenticated.",
      command: "gh",
      args: ["auth", "status"],
      risk: "read-only",
      requiresConfirmation: false,
      check: {
        description: "GitHub CLI authentication is available.",
        command: "gh",
        args: ["auth", "status"]
      },
      undo: {
        description: "No undo is needed for a read-only GitHub authentication check.",
        command: "sh",
        args: ["-c", "true"],
        risk: "read-only",
        requiresConfirmation: false
      }
    },
    {
      provider,
      id: "github.git.init",
      description: "Initialize a local Git repository if this project does not have one.",
      command: "sh",
      args: ["-c", "git init -b main && git config stacksmith.managed true"],
      risk: "reversible",
      requiresConfirmation: true,
      check: {
        description: "Local Git repository exists.",
        command: "test",
        args: ["-d", ".git"]
      },
      undo: {
        description: "Remove the local Git repository only if Stacksmith initialized it.",
        command: "rm",
        args: ["-rf", ".git"],
        risk: "destructive",
        requiresConfirmation: true,
        check: {
          description: "Local Git repository was initialized by Stacksmith.",
          command: "sh",
          args: ["-c", "test \"$(git config --bool stacksmith.managed 2>/dev/null)\" = \"true\""]
        }
      }
    },
    {
      provider,
      id: "github.git.initial-commit",
      description: "Create an initial commit when the project has no commits yet.",
      command: "sh",
      args: ["-c", `git add . && git commit -m "${initialCommitMessage}"`],
      risk: "reversible",
      requiresConfirmation: true,
      check: {
        description: "Local Git repository has a commit.",
        command: "git",
        args: ["rev-parse", "--verify", "HEAD"]
      },
      undo: {
        description: "Undo the Stacksmith-created initial commit only if it is still HEAD.",
        command: "sh",
        args: ["-c", "if git rev-parse --verify HEAD~1 >/dev/null 2>&1; then git reset --soft HEAD~1; else git update-ref -d HEAD; fi"],
        risk: "destructive",
        requiresConfirmation: true,
        check: {
          description: "Latest commit is the Stacksmith initial commit.",
          command: "sh",
          args: ["-c", `test "$(git log -1 --pretty=%B 2>/dev/null)" = "${initialCommitMessage}"`]
        }
      }
    },
    {
      provider,
      id: "github.repo.create",
      description: "Create the GitHub repository.",
      command: "sh",
      args: ["-c", `${repoShell}; gh repo create "$repo" ${visibility} --description ${shSingleQuote(`${manifest.name} generated by Stacksmith`)}`],
      risk: "reversible",
      requiresConfirmation: true,
      check: {
        description: "GitHub repository exists.",
        command: "sh",
        args: ["-c", `${repoShell}; gh repo view "$repo"`]
      },
      undo: {
        description: "Delete the GitHub repository.",
        command: "sh",
        args: ["-c", `${repoShell}; gh repo delete "$repo" --yes`],
        risk: "destructive",
        requiresConfirmation: true,
        check: {
          description: "GitHub repository exists.",
          command: "sh",
          args: ["-c", `${repoShell}; gh repo view "$repo"`]
        }
      }
    },
    {
      provider,
      id: "github.remote.origin",
      description: "Point the local origin remote at the GitHub repository.",
      command: "sh",
      args: ["-c", `${repoUrlShell}; git remote add origin "$repo_url" 2>/dev/null || git remote set-url origin "$repo_url"`],
      risk: "reversible",
      requiresConfirmation: true,
      check: {
        description: "Local origin remote points at the GitHub repository.",
        command: "sh",
        args: remoteMatchesExpected
      },
      undo: {
        description: "Remove origin only when it still points at the Stacksmith-managed GitHub repository.",
        command: "git",
        args: ["remote", "remove", "origin"],
        risk: "reversible",
        requiresConfirmation: true,
        check: {
          description: "Local origin remote points at the GitHub repository.",
          command: "sh",
          args: remoteMatchesExpected
        }
      }
    },
    {
      provider,
      id: "github.repo.push",
      description: "Push the current HEAD to the GitHub main branch.",
      command: "git",
      args: ["push", "-u", "origin", "HEAD:main"],
      risk: "reversible",
      requiresConfirmation: true,
      check: {
        description: "Remote main branch matches local HEAD.",
        command: "sh",
        args: headMatchesRemoteMain
      },
      undo: {
        description: "No direct push undo is possible because GitHub refuses deleting a repository's current default branch; repository deletion tears down the pushed branch.",
        command: "sh",
        args: ["-c", "true"],
        risk: "read-only",
        requiresConfirmation: false
      }
    }
  ];
}

function shSingleQuote(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`;
}

function githubRepoShell(manifest: ProjectManifest): string {
  const owner = manifest.providers.github.owner;
  const ownerAssignment = owner
    ? `repo_owner=${shSingleQuote(owner)}`
    : "repo_owner=\"${GITHUB_OWNER:-$(gh api user --jq .login)}\"";

  return `${ownerAssignment}; repo="$repo_owner/${manifest.slug}"`;
}

function vercelCommandPlan(manifest: ProjectManifest): ExternalCommand[] {
  const provider = "vercel" as const;

  return [
    {
      provider,
      id: "vercel.project.link",
      description: "Link or create the Vercel project.",
      command: "vercel",
      args: ["link", "--project", manifest.slug, "--yes"],
      risk: "reversible",
      requiresConfirmation: true,
      env: ["VERCEL_TOKEN"],
      check: {
        description: "Local Vercel project link exists.",
        command: "test",
        args: ["-f", ".vercel/project.json"]
      },
      undo: {
        description: "Remove the local Vercel project link.",
        command: "rm",
        args: ["-rf", ".vercel"],
        risk: "reversible",
        requiresConfirmation: true
      }
    },
    ...vercelEnvCommands(manifest)
  ];
}

function stripeCommandPlan(manifest: ProjectManifest): ExternalCommand[] {
  const provider = "stripe" as const;
  const webhookUrl = manifest.environments.preview.stripeWebhookUrl ?? "https://stripe-preview.example.com/webhooks";

  return [
    {
      provider,
      id: "stripe.webhook.preview-router",
      description: "Create a Stripe test-mode webhook for the preview router.",
      command: "stripe",
      args: ["webhook_endpoints", "create", "--url", webhookUrl],
      risk: "reversible",
      requiresConfirmation: true,
      env: ["STRIPE_SECRET_KEY"],
      check: {
        description: "Stripe preview webhook endpoint is listed.",
        command: "stripe",
        args: ["webhook_endpoints", "list", "--limit", "100"],
        stdoutIncludes: webhookUrl,
        env: ["STRIPE_SECRET_KEY"]
      },
      undo: {
        description: "Delete a Stripe webhook endpoint by id.",
        command: "stripe",
        args: ["webhook_endpoints", "delete", "$STRIPE_PREVIEW_WEBHOOK_ENDPOINT_ID"],
        risk: "destructive",
        requiresConfirmation: true,
        env: ["STRIPE_SECRET_KEY", "STRIPE_PREVIEW_WEBHOOK_ENDPOINT_ID"]
      }
    }
  ];
}

function cloudRunCommandPlan(manifest: ProjectManifest): ExternalCommand[] {
  const provider = "cloud-run" as const;
  const projectId = cloudRunProjectId(manifest);
  const region = cloudRunRegion(manifest);
  const repository = `${manifest.slug}-images`;
  const apiService = `${manifest.slug}-api`;
  const workerJob = `${manifest.slug}-worker`;

  return [
    {
      provider,
      id: "cloud-run.project.create",
      description: "Create the Google Cloud project Stacksmith will manage for this app.",
      command: "gcloud",
      args: ["projects", "create", projectId, "--name", manifest.name, "--set-as-default"],
      risk: "production-write",
      requiresConfirmation: true,
      check: {
        description: "Google Cloud project exists.",
        command: "gcloud",
        args: ["projects", "describe", projectId]
      },
      undo: {
        description: "Delete the Google Cloud project.",
        command: "gcloud",
        args: ["projects", "delete", projectId, "--quiet"],
        risk: "destructive",
        requiresConfirmation: true
      }
    },
    {
      provider,
      id: "cloud-run.billing.link",
      description: "Link the Google Cloud project to the selected billing account.",
      command: "gcloud",
      args: ["billing", "projects", "link", projectId, "--billing-account", "$GOOGLE_CLOUD_BILLING_ACCOUNT_ID"],
      risk: "production-write",
      requiresConfirmation: true,
      env: ["GOOGLE_CLOUD_BILLING_ACCOUNT_ID"],
      check: {
        description: "Google Cloud project billing is enabled.",
        command: "gcloud",
        args: ["billing", "projects", "describe", projectId, "--format=value(billingEnabled)"],
        stdoutIncludes: "True"
      },
      undo: {
        description: "Unlink billing from the Google Cloud project.",
        command: "gcloud",
        args: ["billing", "projects", "unlink", projectId],
        risk: "production-write",
        requiresConfirmation: true
      }
    },
    {
      provider,
      id: "cloud-run.services.enable",
      description: "Enable Cloud Run, Cloud Build, Artifact Registry, and Scheduler APIs.",
      command: "gcloud",
      args: [
        "services",
        "enable",
        "run.googleapis.com",
        "cloudbuild.googleapis.com",
        "artifactregistry.googleapis.com",
        "cloudscheduler.googleapis.com",
        "--project",
        projectId
      ],
      risk: "reversible",
      requiresConfirmation: true,
      check: {
        description: "Required Google APIs are enabled.",
        command: "gcloud",
        args: ["services", "list", "--enabled", "--project", projectId, "--format=value(config.name)"],
        stdoutIncludes: "run.googleapis.com"
      },
      undo: {
        description: "Disable Cloud Run related Google APIs.",
        command: "gcloud",
        args: [
          "services",
          "disable",
          "run.googleapis.com",
          "cloudbuild.googleapis.com",
          "artifactregistry.googleapis.com",
          "cloudscheduler.googleapis.com",
          "--project",
          projectId,
          "--quiet"
        ],
        risk: "destructive",
        requiresConfirmation: true
      }
    },
    {
      provider,
      id: "cloud-run.artifact-registry.create",
      description: "Create the Docker Artifact Registry repository for Cloud Run builds.",
      command: "gcloud",
      args: [
        "artifacts",
        "repositories",
        "create",
        repository,
        "--repository-format",
        "docker",
        "--location",
        region,
        "--description",
        `Stacksmith images for ${manifest.name}`,
        "--project",
        projectId
      ],
      risk: "production-write",
      requiresConfirmation: true,
      check: {
        description: "Artifact Registry repository exists.",
        command: "gcloud",
        args: ["artifacts", "repositories", "describe", repository, "--location", region, "--project", projectId]
      },
      undo: {
        description: "Delete the Artifact Registry repository.",
        command: "gcloud",
        args: ["artifacts", "repositories", "delete", repository, "--location", region, "--project", projectId, "--quiet"],
        risk: "destructive",
        requiresConfirmation: true
      }
    },
    {
      provider,
      id: "cloud-run.api.deploy",
      description: "Deploy the scale-to-zero API service to Cloud Run.",
      command: "gcloud",
      args: [
        "run",
        "deploy",
        apiService,
        "--source",
        ".",
        "--region",
        region,
        "--allow-unauthenticated",
        "--min-instances",
        "0",
        "--timeout",
        "3600",
        "--project",
        projectId
      ],
      risk: "reversible",
      requiresConfirmation: true,
      check: {
        description: "Cloud Run API service exists.",
        command: "gcloud",
        args: ["run", "services", "describe", apiService, "--region", region, "--project", projectId]
      },
      undo: {
        description: "Delete the Cloud Run API service.",
        command: "gcloud",
        args: ["run", "services", "delete", apiService, "--region", region, "--project", projectId, "--quiet"],
        risk: "destructive",
        requiresConfirmation: true
      }
    },
    {
      provider,
      id: "cloud-run.job.worker.deploy",
      description: "Deploy the background worker as a Cloud Run Job.",
      command: "gcloud",
      args: [
        "run",
        "jobs",
        "deploy",
        workerJob,
        "--source",
        ".",
        "--region",
        region,
        "--task-timeout",
        "3600",
        "--project",
        projectId
      ],
      risk: "reversible",
      requiresConfirmation: true,
      check: {
        description: "Cloud Run worker job exists.",
        command: "gcloud",
        args: ["run", "jobs", "describe", workerJob, "--region", region, "--project", projectId]
      },
      undo: {
        description: "Delete the Cloud Run worker job.",
        command: "gcloud",
        args: ["run", "jobs", "delete", workerJob, "--region", region, "--project", projectId, "--quiet"],
        risk: "destructive",
        requiresConfirmation: true
      }
    },
    {
      provider,
      id: "cloud-run.job.worker.execute",
      description: "Execute the background worker Cloud Run Job.",
      command: "gcloud",
      args: ["run", "jobs", "execute", workerJob, "--region", region, "--project", projectId],
      risk: "reversible",
      requiresConfirmation: true,
      undo: {
        description: "Cloud Run job executions are one-shot and cannot be undone.",
        command: "stacksmith",
        args: ["noop", "cloud-run.job.worker.execute"],
        risk: "read-only",
        requiresConfirmation: false
      }
    }
  ];
}

const vercelEnvMappings = [
  ["APP_URL", "production"],
  ["API_URL", "production"],
  ["FILES_URL", "production"],
  ["DATABASE_URL", "production"],
  ["DIRECT_DATABASE_URL", "production"],
  ["NEXT_PUBLIC_SENTRY_DSN", "production"],
  ["NEXT_PUBLIC_MIXPANEL_TOKEN", "production"]
] as const;

function vercelEnvCommands(manifest: ProjectManifest): ExternalCommand[] {
  return vercelEnvMappings.map(([name, environment]) => ({
    provider: "vercel" as const,
    id: `vercel.env.${environment}.${name}`,
    description: `Set ${name} for the Vercel ${environment} environment from local env.`,
    command: "vercel",
    args: ["env", "add", name, environment],
    risk: environment === "production" ? "production-write" as const : "reversible" as const,
    requiresConfirmation: true,
    env: ["VERCEL_TOKEN", name],
    stdinFromEnv: name,
    check: {
      description: `${name} exists in the Vercel ${environment} environment.`,
      command: "vercel",
      args: ["env", "ls", environment],
      stdoutIncludes: name,
      env: ["VERCEL_TOKEN"]
    },
    undo: {
      description: `Remove ${name} from the Vercel ${environment} environment.`,
      command: "vercel",
      args: ["env", "rm", name, environment, "--yes"],
      risk: environment === "production" ? "production-write" as const : "reversible" as const,
      requiresConfirmation: true,
      env: ["VERCEL_TOKEN"]
    }
  }));
}

export function allProviderCommandPlans(manifest: ProjectManifest): ExternalCommand[] {
  return (Object.keys(manifest.providers) as ProviderId[])
    .filter((provider) => manifest.providers[provider].enabled)
    .flatMap((provider) => providerCommandPlan(provider, manifest));
}
